apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/rdepot-app.statefulset.yaml
  - resources/rdepot-app.service.yaml

images:
  - name: rdepot-app
    newName: openanalytics/rdepot-app
    newTag: 2.0.0

configMapGenerator:
  - files:
      - config/application.yml
    name: rdepot-app
