apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/rdepot-app.statefulset.yaml
  - resources/rdepot-app.service.yaml
  - resources/rdepot-db-init.job.yaml

configMapGenerator:
  - files:
      - config/rdepot.sql
    name: rdepot-db-init
  - files:
      - config/application.yml
      - config/authentication.yml
    name: rdepot-config

namespace: rdepot

