apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../demo

patches:
  - path: patches/rdepot-repo.statefulset.yaml
  - path: patches/rdepot-app.statefulset.yaml
  - path: patches/rdepot-db.statefulset.yaml
