apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../demo
patchesStrategicMerge:
- patches/rdepot-repo.statefulset.yaml
- patches/rdepot-app.statefulset.yaml
- patches/rdepot-db.statefulset.yaml

