apiVersion: apps/v1
kind: Statefulset
metadata:
  name: rdepot-app
spec:
  template:
    spec:
      containers:
      - name: rdepot-db
        image: library/postgres:alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: rdepot-db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rdepot-db-credentials
              key: password

      - name: rdepot-app
        env:
        - name: DB_URL
          value: jdbc:postgresql://localhost:5432/postgres
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rdepot-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rdepot-db-credentials
              key: password

