apiVersion: v1
kind: ConfigMap
metadata:
  name: rdepot-repo
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;
        proxy_read_timeout 600;

        #gzip  on;
        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/sites-enabled/*;
    }
  sites-enabled-rdepot: |
    server {
      listen                80;
      server_name           _;

      location /repo/ {
        root /opt/rdepot;

        satisfy any;

        access_log          /var/log/nginx/repo.access.log;
        error_log           /var/log/nginx/repo.error.log;
        autoindex on;
      }
      
    }

