apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdepot-app
spec:
  selector:
    matchLabels:
      app: rdepot-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rdepot-app
    spec:
      containers:
      - name: ldap
        image: osixia/openldap
        imagePullPolicy: Always
        env:
        - name: LDAP_TLS
          value: 'false'

      - name: rdepot-app
        ports:
        - containerPort: 8080

        image: openanalytics/rdepot-app:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: app-config
          mountPath: /opt/rdepot/rdepot.conf
          subPath: rdepot.conf

        env:
        - name: LDAP_URL
          value: ldap://localhost:389
        - name: LDAP_BASEDN
          value: dc=example,dc=org
        - name: LDAP_USEROU
          value:
        - name: LDAP_LOGINFIELD
          value: cn
        - name: LDAP_NAMEFIELD
          value: description
        - name: LDAP_DEFAULT_ADMINS
          value: admin

        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: rdepot-db-credentials
              key: url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rdepot-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rdepot-db-credentials
              key: password

      volumes:
      - name: app-config
        configMap:
          name: rdepot-app

