apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/app-stateful
  - ../../base/repo

patchesStrategicMerge:
  - patches/rdepot-app.statefulset.yaml

configMapGenerator:
  - files:
    - repositories.sql
    name: init-repositories-script

