apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - resources/rdepot-repo.service.yaml
  - resources/rdepot-repo.statefulset.yaml

images:
  - name: rdepot-repo
    newName: openanalytics/rdepot-repo
    newTag: 2.3.0

configMapGenerator:
  - files:
      - config/sites-enabled-rdepot
      - config/nginx.conf
    name: rdepot-repo
