apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/rdepot-repo.service.yaml
- resources/rdepot-repo.statefulset.yaml

configMapGenerator:
  - files:
      - config/sites-enabled-rdepot
      - config/nginx.conf
    name: rdepot-repo

namespace: rdepot

