apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rdepot-repo
spec:
  template:
    spec:
      containers:
        - name: gatekeeper
          image: keycloak/keycloak-gatekeeper:7.0.0
          args:
            - --config=/etc/secrets/gatekeeper.yaml
          ports:
            - name: http-oidc 
              containerPort: 3000
          volumeMounts:
            - name: gatekeeper-config
              mountPath: /etc/secrets
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 500Mi
      volumes:
        - name: gatekeeper-config
          secret:
            secretName: gatekeeper-config


