apiVersion: apps/v1
kind: Statefulset
metadata:
  name: rdepot-app
spec:
  template:
    spec:
      initContainers:
        - name: init-repositories
          image: jbergknoff/postgresql-client
          command: ["psql", "--no-password", "--file=/tmp/repositories.sql"]
          env:
          - name: PGPASSFILE
            value: /tmp/pgpass/.pgpass
          volumeMounts:
          - name: pgpassfile
            mountPath: "/tmp/pgpass"
            readOnly: true
          - name: init-repositories-script
            mountPath: "/tmp/repositories.sql"
            subPath: repositories.sql

      containers:
      - name: rdepot-app
        env:
        - name: LDAP_URL
          value: ldap://oa-rdepot-ldap:389
        - name: LDAP_BASEDN
          value: dc=example,dc=org
        - name: LDAP_USEROU
          value: ""
        - name: LDAP_LOGINFIELD
          value: cn
        - name: LDAP_NAMEFIELD
          value: description
        - name: LDAP_DEFAULT_ADMINS
          value: admin
      
      volumes:
      - name: pgpassfile
        secret:
          secretName: rdepot-db-credentials
          items:
          - key: pgpassfile
            mode: 0600
            path: .pgpass
      - name: init-repositories-script
        configMap:
          name: init-repositories-script
