apiVersion: v1
kind: Service
metadata:
  name: rdepot-client
  labels:
    app: rdepot-client
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: rdepot-client
