apiVersion: v1
kind: Service
metadata:
  name: rdepot-repo
  labels:
    app: rdepot-repo
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http-api
  selector:
    app: rdepot-repo
 
