apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/app-stateful

patchesStrategicMerge:
  - patches/rdepot-app.statefulset.yaml

secretGenerator:
  - files:
      - secrets/authentication.yml
    name: rdepot-app-auth

