apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/crane.deployment.yaml
  - resources/crane.service.yaml

configMapGenerator:
  - files:
      - config/application.yml
    name: crane

images:
  - name: crane
    newName: openanalytics/crane-snapshot
    newTag: 0.2.0-SNAPSHOT-20230104.135749

