apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-rdepot

resources:
  - ../../base/app-stateful
  - ../../base/repo
  - ../../base/client-deployment
  - resources/rdepot-db.service.yaml
  - resources/rdepot-db.statefulset.yaml
  - resources/rdepot.ingress.yaml

patches:
  - path: patches/rdepot-app.statefulset.yaml
  - path: patches/rdepot-client.deployment.yaml
  - path: patches/rdepot-repo.statefulset.yaml

configMapGenerator:
  - name: rdepot-app
    files:
      - config/application.yml
      - config/authentication.yml
    behavior: replace

secretGenerator:
  - literals:
      - username=rdepot
      - password=rdepot123
    name: rdepot-db-credentials
