apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/app-stateful
  - ../../base/repo
  - resources/rdepot-db.service.yaml
  - resources/rdepot-db.statefulset.yaml

patchesStrategicMerge:
  - patches/rdepot-app.statefulset.yaml
  - patches/rdepot-repo.statefulset.yaml
  - patches/rdepot-db-init.job.yaml

configMapGenerator:
  - name: rdepot-app
    files:
      - config/application.yml
      - config/authentication.yml
    behavior: replace

secretGenerator:
  - literals:
      - username=rdepot
      - password=rdepot123
    name: rdepot-db-credentials

namespace: demo-rdepot

