apiVersion: v1
kind: Service
metadata:
  name: crane
  labels:
    app: crane
spec:
  clusterIP: None
  ports:
  - name: http-crane
    protocol: TCP
    port: 80
    targetPort: 9080
  selector:
    app: crane
 
