apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/repo

patches:
  - path: patches/rdepot-repo.statefulset.yaml
  - path: patches/rdepot-repo.service.yaml

secretGenerator:
  - files:
      - secrets/gatekeeper.yaml
    name: gatekeeper-config
