apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rdepot-app
spec:
  template:
    spec:
      initContainers:
        - name: init-repositories
          image: jbergknoff/postgresql-client
          command: ["psql", "--no-password", "--file=/tmp/repositories.sql"]
          volumeMounts:
            - name: init-repositories-script
              mountPath: "/tmp/repositories.sql"
              subPath: repositories.sql

      containers:

      volumes:
        - name: init-repositories-script
          configMap:
            name: init-repositories-script

