apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - resources/rdepot-client.deployment.yaml
  - resources/rdepot-client.service.yaml

images:
  - name: rdepot-client
    newName: openanalytics/rdepot-client
    newTag: 2.3.0
