apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rdepot-app
spec:
  selector:
    matchLabels:
      app: rdepot-app
  serviceName: rdepot-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rdepot-app
    spec:
      containers:
        - name: rdepot-app
          image: rdepot-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: DB_URL
              value: ""
            - name: DB_USERNAME
              value: ""
            - name: DB_PASSWORD
              value: ""
          resources:
            requests:
              memory: 2Gi
              cpu: 250m
          volumeMounts:
            - name: app-config
              mountPath: /opt/rdepot/application.yml
              subPath: application.yml
      volumes:
        - name: app-config
          configMap:
            name: rdepot-app
