apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/repo-api

patchesStrategicMerge:
  - patches/rdepot-repo.statefulset.yaml
  - patches/rdepot-repo.service.yaml

configMapGenerator:
  - files:
      - config/application.yml
    name: crane

images:
  - name: crane
    newName: openanalytics/crane
    newTag: 0.1.0

