apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/rdepot-repo.service.yaml
- resources/rdepot-repo.statefulset.yaml

images:
  - name: rdepot-repo
    newName: openanalytics/rdepot-repo
    newTag: 1.5.0

