apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rdepot-repo
spec:
  # template:
  #   spec:
  #     containers:
  #       - name: rdepot-repo-proxy
  #         command: ["sleep", "3600"]
  volumeClaimTemplates:
    - metadata:
        name: repository
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "1Gi"
