apiVersion: batch/v1
kind: Job
metadata:
  name: rdepot-db-init
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgresql
          env:
            - name: PGHOST
              value: rdepot-db
      containers:
      - name: rdepot-db-init
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: username
              name: rdepot-db-credentials
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: rdepot-db-credentials
        - name: PGHOST
          value: rdepot-db
        - name: PGDATABASE
          value: rdepot

