apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/rdepot-client.deployment.yaml
  - resources/rdepot-client.service.yaml

images:
  - name: rdepot-client
    newName: openanalytics/rdepot-client
    newTag: 2.0.0

configMapGenerator:
  - files:
      - config/application.yml
    name: rdepot-app
