declarative: true
repositories:
  - name: demo
    publication-uri: http://rdepot-repo/repo/demo
    server-address: http://rdepot-repo:8080/demo

access-token:
  lifetime-default: 30
  lifetime-configurable: true
  length: 32
  allowed-characters: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789

# Database related properties
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://oa-rdepot-db:5432/rdepot
  username: rdepot
  password: mysecretpassword

# Email related properties
email:
  password:
  username:
  from:
  smtp:
    host:
    port:
    auth:
    starttls:

# Package upload related properties
package:
  upload:
    dir: /opt/rdepot

# Repository generation related properties
repository:
  generation:
    dir: /opt/rdepot/generated

spring:
  liquibase:
    enabled: true

server:
  servlet:
    context-path: /server
  error:
    include-stacktrace: never
    path: /error

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false

springdoc:
  pathsToMatch: /api/v2/**
  api-docs:
    path: /v2/api-docs
  swagger-ui:
    path: /docs/api.html
    disable-swagger-default-url: true
    url: /v2/api-docs
    display-query-params: true
  default-produces-media-type: application/json

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-4r [%t] %5p traceId=%X{traceIdMDC} %c{1} : %m %n"
  level:
    liquibase:
      parser: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO

#storage related properties
localStorage:
  maxRequestSize: 10

storage:
  implementation: local
