apiVersion: batch/v1
kind: Job
metadata:
  name: rdepot-db-init
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgresql
          image: busybox
          command: [ "sh", "-c", "until nc postgresql 5432; do echo waiting for postgresql; sleep 2; done;"]
      containers:
      - name: rdepot-db-init
        image: jbergknoff/postgresql-client
        command: ["psql", "--no-password", "--file=/tmp/rdepot.sql"]
        volumeMounts:
        - name: init-script
          mountPath: "/tmp/rdepot.sql"
          subPath: rdepot.sql
      volumes:
      - name: init-script
        configMap:
          name: rdepot-db-init

